#!/usr/bin/env node
/**
 * Bundles src/csv-cli.ts (with FiBuKI's own lib/import parsers) into the
 * self-contained scripts/fibuki-csv.mjs the plugin ships. The bundle is
 * committed, so installing the plugin needs no build step; rebuild after
 * touching lib/import or src/. `--check` compares without writing, and
 * tests/openai-plugin-csv.test.mjs fails if the
 * committed bundle is stale.
 *
 * esbuild comes from functions/node_modules (installed there already).
 */

import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../..");
const require = createRequire(resolve(repoRoot, "functions/package.json"));
const esbuild = require("esbuild");

const check = process.argv.includes("--check");
const outfile = resolve(here, "scripts/fibuki-csv.mjs");

const result = await esbuild.build({
  entryPoints: [resolve(here, "src/csv-cli.ts")],
  outfile,
  write: !check,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  alias: { "@": repoRoot },
  banner: {
    js: "#!/usr/bin/env node\n// GENERATED by integrations/openai-plugin/build.mjs from src/csv-cli.ts and lib/import. Do not edit.",
  },
  legalComments: "none",
  logLevel: "info",
});

if (check) {
  const fresh = result.outputFiles[0].text;
  if (fresh !== readFileSync(outfile, "utf8")) {
    console.error("scripts/fibuki-csv.mjs is stale. Run: node integrations/openai-plugin/build.mjs");
    process.exit(1);
  }
  console.log("scripts/fibuki-csv.mjs is up to date");
}
